// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/S1lvesterTake/marketplace-api/application/use_case/create_product"
	"github.com/S1lvesterTake/marketplace-api/infrastructure/persistance/db"
	"github.com/S1lvesterTake/marketplace-api/infrastructure/transport/http"
	"github.com/jinzhu/gorm"
)

// Injectors from container.go:

func CreateProductHandler(db2 *gorm.DB) create_product.CreateProductHandler {
	infrastructureRequest := request.NewRequest()
	productRepository := db.NewProductRepository(db2)
	createProductHandler := create_product.NewCreateProductHandler(infrastructureRequest, productRepository)
	return createProductHandler
}
